Fix dict operation get on None type in event_detail_to_str()
Returning {} instead on None so the follow on dict get() will not
fail with AttributeError: 'NoneType' object has no attribute 'get'